# Generated by Django 2.2.4 on 2019-08-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetrequest', '0007_auto_20190831_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
