# Generated by Django 2.2.4 on 2019-08-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetrequest', '0010_auto_20190831_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeType',
            new_name='EmployeeType',
        ),
    ]
