# Generated by Django 2.2.4 on 2019-08-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetrequest', '0011_auto_20190831_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='lastdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
