# Generated by Django 2.2.4 on 2019-09-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetrequest', '0012_ticket_lastdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmaster',
            name='status',
            field=models.CharField(blank=True, choices=[('Instock', 'Instock'), ('Allocate', 'Allocate'), ('Scarp', 'Scarp')], max_length=20, null=True),
        ),
    ]
